# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: boat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nboat.proto\x12\x0fPolyVesselProto\"\x9c\x03\n\x0fTelemetryPacket\x12\x0e\n\x06\x62oatID\x18\x01 \x02(\t\x12\x13\n\x0b\x63odeVersion\x18\x02 \x02(\t\x12\x0f\n\x07GPS_lat\x18\x03 \x02(\t\x12\x0f\n\x07GPS_lon\x18\x04 \x02(\t\x12\x15\n\rGPS_speed_mps\x18\x05 \x02(\r\x12\x17\n\x0fIMU_heading_deg\x18\x06 \x02(\r\x12\x15\n\rIMU_pitch_deg\x18\x07 \x02(\x05\x12\x14\n\x0cIMU_roll_deg\x18\x08 \x02(\x05\x12\x15\n\rmotor_speed_L\x18\t \x02(\x05\x12\x15\n\rmotor_speed_R\x18\n \x02(\x05\x12\x16\n\x0e\x62\x61t_voltage_mV\x18\x0b \x02(\x05\x12\x16\n\x0e\x62\x61t_current_mA\x18\x0c \x02(\x05\x12\x15\n\rbat_temp_degC\x18\r \x02(\x05\x12\x33\n\x04mode\x18\x0e \x02(\x0e\x32%.PolyVesselProto.TelemetryPacket.Mode\x12\x19\n\x11max_command_index\x18\x0f \x02(\x05\" \n\x04Mode\x12\x0c\n\x08WAYPOINT\x10\x00\x12\n\n\x06MANUAL\x10\x01\"1\n\x07\x43ommand\x12\x15\n\rcommand_index\x18\x01 \x02(\r\x12\x0f\n\x07message\x18\x02 \x02(\t\"K\n\x0cVesselUpdate\x12*\n\x08\x63ommands\x18\x02 \x03(\x0b\x32\x18.PolyVesselProto.Command\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1b\n\tPingHello\x12\x0e\n\x06\x62oatID\x18\x01 \x02(\t2Q\n\nPolyVessel\x12\x43\n\x04Ping\x12\x1a.PolyVesselProto.PingHello\x1a\x1d.PolyVesselProto.VesselUpdate\"\x00')



_TELEMETRYPACKET = DESCRIPTOR.message_types_by_name['TelemetryPacket']
_COMMAND = DESCRIPTOR.message_types_by_name['Command']
_VESSELUPDATE = DESCRIPTOR.message_types_by_name['VesselUpdate']
_PINGHELLO = DESCRIPTOR.message_types_by_name['PingHello']
_TELEMETRYPACKET_MODE = _TELEMETRYPACKET.enum_types_by_name['Mode']
TelemetryPacket = _reflection.GeneratedProtocolMessageType('TelemetryPacket', (_message.Message,), {
  'DESCRIPTOR' : _TELEMETRYPACKET,
  '__module__' : 'boat_pb2'
  # @@protoc_insertion_point(class_scope:PolyVesselProto.TelemetryPacket)
  })
_sym_db.RegisterMessage(TelemetryPacket)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'boat_pb2'
  # @@protoc_insertion_point(class_scope:PolyVesselProto.Command)
  })
_sym_db.RegisterMessage(Command)

VesselUpdate = _reflection.GeneratedProtocolMessageType('VesselUpdate', (_message.Message,), {
  'DESCRIPTOR' : _VESSELUPDATE,
  '__module__' : 'boat_pb2'
  # @@protoc_insertion_point(class_scope:PolyVesselProto.VesselUpdate)
  })
_sym_db.RegisterMessage(VesselUpdate)

PingHello = _reflection.GeneratedProtocolMessageType('PingHello', (_message.Message,), {
  'DESCRIPTOR' : _PINGHELLO,
  '__module__' : 'boat_pb2'
  # @@protoc_insertion_point(class_scope:PolyVesselProto.PingHello)
  })
_sym_db.RegisterMessage(PingHello)

_POLYVESSEL = DESCRIPTOR.services_by_name['PolyVessel']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TELEMETRYPACKET._serialized_start=32
  _TELEMETRYPACKET._serialized_end=444
  _TELEMETRYPACKET_MODE._serialized_start=412
  _TELEMETRYPACKET_MODE._serialized_end=444
  _COMMAND._serialized_start=446
  _COMMAND._serialized_end=495
  _VESSELUPDATE._serialized_start=497
  _VESSELUPDATE._serialized_end=572
  _PINGHELLO._serialized_start=574
  _PINGHELLO._serialized_end=601
  _POLYVESSEL._serialized_start=603
  _POLYVESSEL._serialized_end=684
# @@protoc_insertion_point(module_scope)
